### ISSUE TITLE
Which version of rlkit do you use?

### ISSUE THREAD

**Issue by jeffwillette** [Mattief/VIREL#1]
Hi. I see you are the coauthor of the VIREL paper and I opened an accompanying issue at https://github.com/AnujMahajanOxf/VIREL/issues/1. I am wondering if you know the exact commit of https://github.com/vitchyr/rlkit that you used with VIREL. It seems that rlkit has changed quite a lot and doesn't work with the VIREL code anymore. the commit with the tag `v0.1.2` is close, but I still can't get the VIREL code to run without error.

**Comment by Mattief** [comment]
Hey, I'm really sorry but I don't :( Anuj implemented this so I think you
are probably better asking him. Let me know if you are struggling to get
hold of him and I'll pass on your details.

Mattie.

**Comment by jeffwillette** [comment]
ok, I opened an issue on his Github repo as well ( AnujMahajanOxf/VIREL#1), so if you could notify him of that in case he doesn't watch it regularly, I would appreciate it. I will close this issue now
